---
title: "Overview"
format: html
---

# Module Title

**Variant calling**

# Authors

Content by Qasim Ayub

# Duration

2.5h

# Key topics

In this module, learners will look at

-   DNA variation

-   Variant calling basics and steps in variant detection

-   Common sources of error in variant calling

-   Population level variant data, genomic context and clinical relevance of variants.

# Learning outcomes

By the end of this module, you should be able to:

-   Understand various types of variation and how they are ascertained.
-   Understand how variant calls are made.
-   Assess variant quality and visualise variants.
-   Annotate variants and assess consequences.

# Activities

-   Lecture 0.5h

-   Practical exercises 2h

# Manual and practical exercises

[Module manual](module3_manual.qmd)

[Exercises](module3_exercises.qmd)

# Lecture notes or scripts

[Recording of the Variant Calling module from the 2022 NGS Asia Course delivered by Petr Danecek.](https://www.youtube.com/watch?v=2l3vbLyO8Sg&list=PLfovZnX0TvKtCjKYWitzUN6f_PwdUHeSu&index=6)

# Teaching guidance

[Instructor notes](module3_instructor_notes.qmd)

# Datasets

We recommend that you follow the exercises using the course virtual machine.

The datasets used in this exercise are stored on the virtual machine.

# Platform Guidance

[Guide](module3_platform_guidance.qmd)
