---
title: "Overview"
format: html
---

# Module Title

Structural Variation Calling

# Authors

This tutorial was written by Jacqui Keane and Thomas Keane.

# Duration

3.5 hours

# Key topics

# Learning outcomes

-   Understand the background and theory of structural variation

-   Call structural variants using standard tools

-   Visualise structural variants using standard tools

-   Call structural variants from long read data

-   Use bedtools to do regional comparisons over genomic coordinates

# Activities

-   Lecture: 1 hour

-   Practical exercises: 2.5 hours

# Manual

[Module manual](module4_manual.qmd)

[Exercises](module4_exercises.qmd)

# Lecture recording, notes and scripts

[Lecture on Structural Variant Calling from the 2022 NGS Asia course, delivered by Thomas Keane](https://www.youtube.com/watch?v=80tpolAIJ8E&list=PLfovZnX0TvKtCjKYWitzUN6f_PwdUHeSu&index=7)

# Teaching guidance

[Instructor notes](module4_instructor_notes.qmd)

# Datasets

We recommend that you follow the exercises using the course virtual machine.

The datasets used in this exercise are stored on the virtual machine.

# Platform Guidance

[Guide](module4_platform_guidance.qmd)
